### ISSUE TITLE
PHP Notice: Trying to get property of non-object in .../ProcessChangelog/ProcessChangelogHooks.module:283

### ISSUE THREAD

**Issue by adrianbj** [teppokoivula/ProcessChangelog#14]
Just noticed this - not a big deal, but would be nice to cleanup still.

**Comment by teppokoivula** [comment]
@adrianbj, thanks for reporting this. I've tried to reproduce the issue based on the discussion at the support forum thread, but so far I've no clue what this could be about.

I'm closing this issue for now, but please let me know if you have any additional information and I'll re-open it. Thanks!
