### ISSUE TITLE
Page number styling

### ISSUE THREAD

**Issue by adrianbj** [teppokoivula/ProcessChangelog#15]
Hi @teppokoivula - it looks like there's a styling issue with the page numbers. Every time I click to a new page, it looks like this:

![image](https://user-images.githubusercontent.com/871211/37222724-028cd7c2-2383-11e8-90ea-3ee28a6ac661.png)

Then if I reload the page it's fine again. I have tried a couple of different sites, servers, and browsers with the same result.

Also, it doesn't seem like there is any visual indication of the current page.

Running 1.5.4 on PW 4.0.95 and Uikit theme.

Let me know if you have any trouble reproducing and I'll dig further.

Thanks!

**Comment by teppokoivula** [comment]
Thanks @adrianbj. Turns out AdminThemeUikit changes default MarkupPagerNav classes, so the pager this module builds from the scratch no longer matched those. Latest commit checks for MarkupPagerNav config settings and uses those if possible, so this should be fixed now.

**Comment by adrianbj** [comment]
Looks good now - thanks!
