### ISSUE TITLE
Fatal error: Allowed memory

### ISSUE THREAD

**Issue by tbba** [teppokoivula/ProcessChangelog#16]
With the CangeLog activated I start receiving errors with the PW Backup:

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in //www-office/wire/core/WireDatabaseBackup.php on line 1269 

Uninstalling ChangeLog makes the backups run fine again.

ProcessWire 3.0.125 ,
Changelog   1.5.5
PHP 7.2 Apache 2.4
256 MB Memory

**Comment by tbba** [comment]
For curiosity - I re-installed the plugin - Backup still works.
So maybe Changelog had corrupted data that was removed during the prevoius de-installation.
An easy way of killing all saved data at once (for users with that permission) maybe would help?
I will monitor this further.

**Comment by tbba** [comment]
Sorry the info comes in little pieces:
From a backup (one that worked) I could see the content of process_changelog building up.
80.000 rows although the data max age was 1 week. So maybe the data was not corrupt but far to much for the memory available?
That came from a cron job running every 5 minutes and grabbing some information from the web to some field.  
What about more limit options - and is there a way not to logging system events, only user events. To see what editors are doing this would be enough in my case.

**Comment by teppokoivula** [comment]
Hey @tbba! Sorry for taking unbearably long to respond. Your finding seems reasonable; I'm not particularly familiar with WireDatabaseBackup, but it could indeed cause issues if you have a lot of data. < 100k rows in a database crashing the system sounds a bit odd, but it _could_ happen.

I have a site where I forgot to add a limit, and now there are ~2.5 million records (which kind of makes things slow), so was just thinking that I should really add a "prune now" feature. Additionally I think there should be a "limit to x rows" setting, and your idea of disabling logging for system users is great – though I'd rather make that "disable logging for selected roles".

I've created new issues for these enhancements. For the time being I'm closing this issue – though please let me know if there's still something else wrong.
