### ISSUE TITLE
Date breaks on hyphen

### ISSUE THREAD

**Issue by adrianbj** [teppokoivula/ProcessChangelog#22]
Hey @teppokoivula - really minor issue, but it might be nice to use a non-breaking hypen/dash (or some other approach) in the date so that this doesn't happen:

![image](https://user-images.githubusercontent.com/871211/66435045-cc38e800-e9d8-11e9-9e36-d215e89c0ae8.png)

Thanks!

**Comment by teppokoivula** [comment]
Thanks @adrianbj, I'll make sure to dig into this the next time I update this module :)

**Comment by teppokoivula** [comment]
Implemented in the latest release.
