### ISSUE TITLE
Tracking core notifications

### ISSUE THREAD

**Issue by adrianbj** [teppokoivula/ProcessChangelog#23]
Hey @teppokoivula - I know no-one should ever install the PW core notifications module, but I am working on a site where it is installed and it results in huge numbers of calls to changelog.

Something like this:
```
$info = parse_url($_SERVER['REQUEST_URI']);
$queryString = isset($info['query']) ? $info['query'] : '';
if(strpos($queryString, 'Notifications=update') !== false) return;
```
should sort it out :)

**Comment by teppokoivula** [comment]
Thanks, makes sense to me. This should be fixed in the latest release :)
