### ISSUE TITLE
Editing alternate template / parent users results in "moved" status

### ISSUE THREAD

**Issue by adrianbj** [teppokoivula/ProcessChangelog#31]
Hi @teppokoivula - I am seeing an interesting situation when editing a user with an alternate parent / template. Instead of saying the page was edited, it's saying it was saved. I think this is likely a result of the way the PW core handles editing of these users - I think it might actually temporarily move them to Admin > Access > Users and then back again after saving. Perhaps @ryancramerdesign could confirm this. Not sure if there is a way you can work around this, or perhaps it will go away if Ryan can address this: https://github.com/processwire/processwire-issues/issues/1457

Thanks.

**Comment by teppokoivula** [comment]
Thanks for reporting this. To be honest I'm somewhat tempted to wait and see if that issue gets resolved and if it helps, but I'll see if I can find some time to set up a test environment and check out what's going on here.

I don't currently have any sites with alternate parent/template for users — last time I tried it didn't seem to work that well for my use cases, so had to revert and take another route.

**Comment by adrianbj** [comment]
Thanks @teppokoivula - I hope Ryan does spend a little more time on that feature because I really like the concept and find it really useful. It just needs some refinement and bug fixes.

**Comment by teppokoivula** [comment]
@adrianbj, just a quick heads-up: managed to reproduce this in the latest dev version. It's a new issue, introduced by https://github.com/processwire/processwire/commit/fc0db2bb224075e7d6e4105619a2293a5ca4b7a0.

For the time being I've no idea what's going on in there, and if this is expected thing or a core issue, but I think it would be best if we could have @ryancramerdesign look at this. Should probably open a new issue in the ProcessWire repository — but I'd like to have a better idea what's going on before doing that :)

**Comment by teppokoivula** [comment]
Opened a new issue about this here: https://github.com/processwire/processwire-issues/issues/1505. I could likely work around this new behaviour in the module, but I'd first like to know if it's intentional or not.

**Comment by adrianbj** [comment]
Thanks for your time investigating and reporting this!
