### ISSUE TITLE
PHP Warning: Undefined array key "Previous page name" in ProcessChangelog.module:805

### ISSUE THREAD

**Issue by matjazpotocnik** [teppokoivula/ProcessChangelog#36]
This happens when page is trashed.

And this: JQMIGRATE: jQuery.fn.focus() event shorthand is deprecated

**Comment by teppokoivula** [comment]
@matjazpotocnik, the notice should be gone in the latest version of the module.

That being said, I'm not entirely sure why trashing a page would not save previous page name, so it would be great if you could provide any insight into this. I've tried trashing pages from the page tree, dragging them to trash, etc. and have so far been unable to actually reproduce this problem :)

**Comment by matjazpotocnik** [comment]
Fixed, thank you.

I'm not sure how this happened, but I was working on resolving issue 1201, where trash status is not removed when a page is moved out of the trash. I have trashed and then restored many pages, manually changing the trash status, etc.
