### ISSUE TITLE
Can't enter dates

### ISSUE THREAD

**Issue by matjazpotocnik** [teppokoivula/ProcessChangelog#37]
When I select the option "between" I can't enter a date range, the tooltip tells me "Not relevant in this context".

**Comment by teppokoivula** [comment]
Module JS should enable those date inputs when "between" is selected. Sounds line a JS error somewhere. Are there any errors in dev tools console?

I'm not seeing this issue here, tested in current PW master and dev, with debug set to false and "dev".

**Comment by teppokoivula** [comment]
1.14.9 fixes a jQuery 3 issue that might've been related to this. Let me know if it works for you :)

**Comment by matjazpotocnik** [comment]
$when.attr('value');
undefined

$when.prop('value');
'between'

Yes, it's fixed. I'm on "dev". Thank you.

**Comment by matjazpotocnik** [comment]
When I change from "between" to "whenever", both dates are left in their inputs, and "whenever" doesn't work:

![image](https://github.com/teppokoivula/ProcessChangelog/assets/7663992/41154a24-c76f-4dfc-b7d7-24173190722f)

There are over 150 rows in the table, 2 rows (shown in the screenshot) are left when I used the "between" option. Changing from "between" to "within day/week/month/year" is working as expected. No JS errors in the console.

**Comment by teppokoivula** [comment]
Thanks, this should now be fixed as well :)

**Comment by matjazpotocnik** [comment]
Unfortunately, it doesn't :-) Dates are cleared, history is replaced, but the rows are not refreshed:


https://github.com/teppokoivula/ProcessChangelog/assets/7663992/fd013270-a43d-494d-9268-e900f63faac2

**Comment by teppokoivula** [comment]
Sorry for that — latest version has another fix for this, looks like my earlier change only fixed the case where page was reloaded with filter values in place :)

**Comment by matjazpotocnik** [comment]
Yep, it works now! Thank you for your speedy fixing.
