### ISSUE TITLE
Recording changes to user template / ignoring certain fields

### ISSUE THREAD

**Issue by adrianbj** [teppokoivula/ProcessChangelog#9]
Maybe an unusual situation, but I have a field on the user template which stores the last datetime that the user loaded a page on the site. This is used so I can then highlight new/modified pages for them when they login. The problem is that Changelog is recording a change to their user page every time they visit a page on the site. In your first forum post you state: "This module tracks changes, additions, removals etc. of public (as in "not under admin") pages of your site." Shouldn't this exclude changes to user pages? I actually like the idea of recording changes to user profiles though, so I guess I don't want to see it removed, but I think I do need a solution for my situation. So, maybe an option to ignore certain fields?

Any thoughts?

Thanks!

**Comment by teppokoivula** [comment]
The description should probably be updated, part of that has changed since then (as you can see) :)

An option to ignore certain fields seems to make sense. I'll have to think about this a bit though, i.e. what kind of flexibility is needed, is it global setting or something else, and so on.

**Comment by teppokoivula** [comment]
@adrianbj: it took a while to get here, but this is now implemented. I started seeing a lot of entries for the "notifications" field on the User template, and those started getting kind of annoying. There are now two new config settings for the ProcessChangelogHooks module, one for ignoring specific templates and another for ignoring specific fields.

Thanks for the suggestion :)
